*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 16:35:45 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1aac9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1aac9d0 pid: 20445 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20445, cores: 1)
spawned uWSGI worker 2 (pid: 20448, cores: 1)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 51, in view
    return render_to_response('user_def_temp1.html', {'pageForm': UserDefine.objects.get(username="Hang").pageForm})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: UserDefine matching query does not exist.
[pid: 20445|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 16:35:50 2016] GET /select/template_1/view/ => generated 64810 bytes in 147 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 20448|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 898 bytes} [Fri Feb 12 16:35:50 2016] GET /favicon.ico => generated 3138 bytes in 35 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 51, in view
    return render_to_response('user_def_temp1.html', {'pageForm': UserDefine.objects.get(username="Hang").pageForm})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: UserDefine matching query does not exist.
[pid: 20445|app: 0|req: 2/3] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 16:35:56 2016] GET /select/template_1/view/ => generated 64810 bytes in 88 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 20448|app: 0|req: 2/4] 222.209.181.22 () {40 vars in 874 bytes} [Fri Feb 12 16:36:53 2016] GET / => generated 218404 bytes in 14 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20445|app: 0|req: 3/5] 222.209.181.22 () {42 vars in 927 bytes} [Fri Feb 12 16:37:00 2016] GET /select/ => generated 1626 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20448|app: 0|req: 3/6] 222.209.181.22 () {42 vars in 956 bytes} [Fri Feb 12 16:37:04 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20445|app: 0|req: 4/7] 222.209.181.22 () {42 vars in 977 bytes} [Fri Feb 12 16:37:07 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20448|app: 0|req: 4/8] 222.209.181.22 () {42 vars in 966 bytes} [Fri Feb 12 16:37:46 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20445|app: 0|req: 5/9] 222.209.181.22 () {50 vars in 1147 bytes} [Fri Feb 12 16:37:46 2016] POST /select/template_1/view/ => generated 16893 bytes in 99 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20448|app: 0|req: 5/10] 222.209.181.22 () {44 vars in 941 bytes} [Fri Feb 12 16:37:47 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20445|app: 0|req: 6/11] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 16:37:49 2016] GET /select/template_1/view/ => generated 65041 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20448|app: 0|req: 6/12] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 16:38:01 2016] POST /select/template_1/analysis/ => generated 22 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
