*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:36:46 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe389d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe389d0 pid: 20844 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20844, cores: 1)
spawned uWSGI worker 2 (pid: 20847, cores: 1)
[pid: 20844|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 874 bytes} [Fri Feb 12 17:36:48 2016] GET / => generated 218404 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1057 bytes} [Fri Feb 12 17:37:00 2016] GET / => generated 218404 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1110 bytes} [Fri Feb 12 17:37:02 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 3/4] 222.209.181.22 () {44 vars in 1139 bytes} [Fri Feb 12 17:37:03 2016] GET /select/template_1/ => generated 82701 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 1160 bytes} [Fri Feb 12 17:37:05 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 4/6] 222.209.181.22 () {44 vars in 1149 bytes} [Fri Feb 12 17:37:39 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20847|app: 0|req: 3/7] 222.209.181.22 () {50 vars in 1278 bytes} [Fri Feb 12 17:37:39 2016] POST /select/template_1/view/ => generated 16818 bytes in 104 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20844|app: 0|req: 5/8] 222.209.181.22 () {44 vars in 1078 bytes} [Fri Feb 12 17:37:40 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 4/9] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:37:45 2016] GET /select/template_1/view/ => generated 64827 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 6/10] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:37:45 2016] GET /select/template_1/view/ => generated 64827 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 87, in analysis
    s = UserDefine.objects.get(username="Hang").statics_set.get(key=foreign_key)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 20847|app: 0|req: 5/11] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:37:54 2016] POST /select/template_1/analysis/ => generated 12415 bytes in 35 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:41:12 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15c99d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15c99d0 pid: 20888 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20888, cores: 1)
spawned uWSGI worker 2 (pid: 20891, cores: 1)
[pid: 20888|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:41:16 2016] GET /select/template_1/view/ => generated 64827 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20891|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:41:28 2016] GET /select/template_1/ => generated 82701 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20888|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:41:30 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20891|app: 0|req: 2/4] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:42:08 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20888|app: 0|req: 3/5] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:42:08 2016] POST /select/template_1/view/ => generated 16777 bytes in 179 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20891|app: 0|req: 3/6] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:42:09 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20888|app: 0|req: 4/7] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:42:14 2016] GET /select/template_1/view/ => generated 64779 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 77, in analysis
    if UserDefine.objects.get(username="Hang").statics_set.get(key='arr[0][0]'):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 20891|app: 0|req: 4/8] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:42:24 2016] POST /select/template_1/analysis/ => generated 12403 bytes in 38 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:45:32 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xec09d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xec09d0 pid: 20935 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20935, cores: 1)
spawned uWSGI worker 2 (pid: 20938, cores: 1)
[pid: 20935|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:45:40 2016] GET /select/template_1/view/ => generated 64779 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1080 bytes} [Fri Feb 12 17:45:53 2016] GET / => generated 218404 bytes in 45 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1133 bytes} [Fri Feb 12 17:45:55 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 3/4] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:45:56 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:45:58 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 3/6] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:46:35 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20935|app: 0|req: 4/7] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:46:35 2016] POST /select/template_1/view/ => generated 16705 bytes in 140 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20938|app: 0|req: 4/8] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:46:36 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 5/9] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:46:42 2016] GET /select/template_1/view/ => generated 64743 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 5/10] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:46:53 2016] POST /select/template_1/analysis/ => generated 0 bytes in 156 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 6/11] 222.209.181.22 () {40 vars in 904 bytes} [Fri Feb 12 17:47:21 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20935|app: 0|req: 7/12] 222.209.181.22 () {44 vars in 941 bytes} [Fri Feb 12 17:47:22 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 140, in real_handler
    dim_arr[h] = int(dim_arr[h])
ValueError: invalid literal for int() with base 10: ''
[pid: 20938|app: 0|req: 6/13] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 17:47:25 2016] GET /submit/welcome/realHandler/ => generated 58074 bytes in 95 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 140, in real_handler
    dim_arr[h] = int(dim_arr[h])
ValueError: invalid literal for int() with base 10: ''
[pid: 20935|app: 0|req: 8/14] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 17:47:25 2016] GET /submit/welcome/realHandler/ => generated 57924 bytes in 83 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:49:04 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x23c79d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x23c79d0 pid: 20979 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20979, cores: 1)
spawned uWSGI worker 2 (pid: 20982, cores: 1)
[pid: 20979|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 17:49:10 2016] GET /submit/welcome/realHandler/ => generated 15467 bytes in 50 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20982|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 17:49:10 2016] GET /submit/welcome/realHandler/ => generated 15467 bytes in 42 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:50:35 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb829d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xb829d0 pid: 21023 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21023, cores: 1)
spawned uWSGI worker 2 (pid: 21026, cores: 1)
[pid: 21023|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1035 bytes} [Fri Feb 12 17:50:37 2016] GET /submit/welcome/realHandler/ => generated 15470 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:54:33 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x26dd9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x26dd9d0 pid: 21067 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21067, cores: 1)
spawned uWSGI worker 2 (pid: 21070, cores: 1)
[pid: 21067|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 1080 bytes} [Fri Feb 12 17:54:38 2016] GET / => generated 218404 bytes in 47 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1133 bytes} [Fri Feb 12 17:54:40 2016] GET /select/ => generated 1626 bytes in 34 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:54:41 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 2/4] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:54:43 2016] GET /select/template_1/edit/ => generated 23884 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 3/5] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:55:23 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21067|app: 0|req: 3/6] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:55:23 2016] POST /select/template_1/view/ => generated 16747 bytes in 132 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21070|app: 0|req: 4/7] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:55:24 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 4/8] 222.209.181.22 () {40 vars in 942 bytes} [Fri Feb 12 17:55:29 2016] GET /select/template_1/view/ => generated 64755 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 5/9] 222.209.181.22 () {40 vars in 942 bytes} [Fri Feb 12 17:55:29 2016] GET /select/template_1/view/ => generated 64755 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 5/10] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 17:55:39 2016] POST /select/template_1/analysis/ => generated 0 bytes in 190 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 97, in analysis
    a.multi_count += 1
AttributeError: 'QuerySet' object has no attribute 'multi_count'
[pid: 21070|app: 0|req: 6/11] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 17:55:42 2016] POST /select/template_1/analysis/ => generated 12125 bytes in 403 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 62, in analysis
    ans = ans[2:len(ans) - 2].split("],[")
TypeError: object of type 'NoneType' has no len()
[pid: 21067|app: 0|req: 6/12] 222.209.181.22 () {40 vars in 950 bytes} [Fri Feb 12 17:55:50 2016] GET /select/template_1/analysis/ => generated 56435 bytes in 94 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 7/13] 222.209.181.22 () {42 vars in 1080 bytes} [Fri Feb 12 17:56:22 2016] GET / => generated 218404 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 7/14] 222.209.181.22 () {44 vars in 1133 bytes} [Fri Feb 12 17:56:25 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 8/15] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:56:26 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 8/16] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:56:28 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 9/17] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:57:04 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21067|app: 0|req: 9/18] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:57:04 2016] POST /select/template_1/view/ => generated 17400 bytes in 176 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21070|app: 0|req: 10/19] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:57:05 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 10/20] 222.209.181.22 () {40 vars in 942 bytes} [Fri Feb 12 17:57:09 2016] GET /select/template_1/view/ => generated 65183 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 11/21] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 17:57:20 2016] POST /select/template_1/analysis/ => generated 0 bytes in 175 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 11/22] 222.209.181.22 () {40 vars in 926 bytes} [Fri Feb 12 17:57:32 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21067|app: 0|req: 12/23] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 17:57:32 2016] GET /user_form_folders => generated 3156 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21070|app: 0|req: 12/24] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 17:57:34 2016] GET /submit/welcome/realHandler/ => generated 15600 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21067|app: 0|req: 13/25] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 17:57:34 2016] GET /submit/welcome/realHandler/ => generated 15600 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:59:21 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1aa39d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1aa39d0 pid: 21114 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21114, cores: 1)
spawned uWSGI worker 2 (pid: 21117, cores: 1)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 149, in real_handler
    data_arr[i][j] = d.get(key=foreign_key).intValue
IndexError: list assignment index out of range
[pid: 21114|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 950 bytes} [Fri Feb 12 17:59:24 2016] GET /submit/welcome/realHandler/ => generated 58421 bytes in 130 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:04:22 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x19f69d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x19f69d0 pid: 21158 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21158, cores: 1)
spawned uWSGI worker 2 (pid: 21161, cores: 1)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 145, in real_handler
    data_arr[i][0] = d.get(key=foreign_key).strValue
IndexError: list assignment index out of range
[pid: 21158|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 981 bytes} [Fri Feb 12 18:04:26 2016] GET /submit/welcome/realHandler/ => generated 58504 bytes in 140 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 145, in real_handler
    data_arr[i][0] = d.get(key=foreign_key).strValue
IndexError: list assignment index out of range
[pid: 21161|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 18:04:33 2016] GET /submit/welcome/realHandler/ => generated 58677 bytes in 127 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 145, in real_handler
    data_arr[i][0] = d.get(key=foreign_key).strValue
IndexError: list assignment index out of range
[pid: 21158|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 18:04:33 2016] GET /submit/welcome/realHandler/ => generated 58527 bytes in 88 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:05:17 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x27489d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x27489d0 pid: 21205 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21205, cores: 1)
spawned uWSGI worker 2 (pid: 21208, cores: 1)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 161, in real_handler
    valid_count[k] = lenradio
IndexError: list assignment index out of range
[pid: 21205|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1035 bytes} [Fri Feb 12 18:05:19 2016] GET /submit/welcome/realHandler/ => generated 59738 bytes in 135 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:06:36 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ba89d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ba89d0 pid: 21249 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21249, cores: 1)
spawned uWSGI worker 2 (pid: 21252, cores: 1)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 163, in real_handler
    lencheck = d.get(key='arr[' + str(k) + '][0]').anscount_set.all().multi_count
AttributeError: 'QuerySet' object has no attribute 'multi_count'
[pid: 21249|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1035 bytes} [Fri Feb 12 18:06:38 2016] GET /submit/welcome/realHandler/ => generated 59637 bytes in 132 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Not Found: /m/
[pid: 21252|app: 0|req: 1/2] 203.208.60.222 () {40 vars in 648 bytes} [Fri Feb 12 18:06:58 2016] GET /m/ => generated 3111 bytes in 35 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:10:46 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd9f9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd9f9d0 pid: 21293 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21293, cores: 1)
spawned uWSGI worker 2 (pid: 21296, cores: 1)
[pid: 21293|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 18:10:52 2016] GET /select/template_1/ => generated 82701 bytes in 41 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21296|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 18:10:54 2016] GET /select/template_1/edit/ => generated 23884 bytes in 35 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21296|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 18:11:47 2016] GET /select/success/ => generated 14374 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21293|app: 0|req: 2/4] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 18:11:47 2016] POST /select/template_1/view/ => generated 16743 bytes in 138 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21296|app: 0|req: 3/5] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 18:11:48 2016] GET /user_form_folders => generated 3156 bytes in 10 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21293|app: 0|req: 3/6] 222.209.181.22 () {40 vars in 942 bytes} [Fri Feb 12 18:11:52 2016] GET /select/template_1/view/ => generated 64805 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 117, in analysis
    question=Statics.objects.get(key='arr[' + str(m) + '][0]'))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table question_naire_anscount has no column named key
[pid: 21296|app: 0|req: 4/7] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 18:12:00 2016] POST /select/template_1/analysis/ => generated 14455 bytes in 149 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 62, in analysis
    ans = ans[2:len(ans) - 2].split("],[")
TypeError: object of type 'NoneType' has no len()
[pid: 21293|app: 0|req: 4/8] 222.209.181.22 () {40 vars in 950 bytes} [Fri Feb 12 18:12:11 2016] GET /select/template_1/analysis/ => generated 56435 bytes in 77 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21296|app: 0|req: 5/9] 222.209.181.22 () {40 vars in 896 bytes} [Fri Feb 12 18:12:23 2016] GET / => generated 218404 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21293|app: 0|req: 5/10] 222.209.181.22 () {42 vars in 949 bytes} [Fri Feb 12 18:12:27 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21293|app: 0|req: 6/11] 222.209.181.22 () {42 vars in 978 bytes} [Fri Feb 12 18:12:28 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21296|app: 0|req: 6/12] 222.209.181.22 () {42 vars in 999 bytes} [Fri Feb 12 18:12:30 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21296|app: 0|req: 7/13] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 18:13:12 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21293|app: 0|req: 7/14] 222.209.181.22 () {50 vars in 1169 bytes} [Fri Feb 12 18:13:12 2016] POST /select/template_1/view/ => generated 16501 bytes in 156 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21296|app: 0|req: 8/15] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:13:13 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21293|app: 0|req: 8/16] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 18:13:15 2016] GET /select/template_1/view/ => generated 64808 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 117, in analysis
    question=Statics.objects.get(key='arr[' + str(m) + '][0]'))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table question_naire_anscount has no column named key
[pid: 21296|app: 0|req: 9/17] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 18:13:25 2016] POST /select/template_1/analysis/ => generated 14447 bytes in 136 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 21293|app: 0|req: 9/18] 220.181.108.109 () {36 vars in 473 bytes} [Fri Feb 12 18:14:53 2016] GET / => generated 218404 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:16:49 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a709d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a709d0 pid: 21365 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21365, cores: 1)
spawned uWSGI worker 2 (pid: 21368, cores: 1)
[pid: 21365|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 896 bytes} [Fri Feb 12 18:16:51 2016] GET / => generated 218404 bytes in 49 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21368|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 949 bytes} [Fri Feb 12 18:16:52 2016] GET /select/ => generated 1626 bytes in 39 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21365|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 978 bytes} [Fri Feb 12 18:16:53 2016] GET /select/template_1/ => generated 82701 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21368|app: 0|req: 2/4] 222.209.181.22 () {42 vars in 999 bytes} [Fri Feb 12 18:16:55 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21365|app: 0|req: 3/5] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 18:17:34 2016] GET /select/success/ => generated 14374 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21368|app: 0|req: 3/6] 222.209.181.22 () {50 vars in 1169 bytes} [Fri Feb 12 18:17:34 2016] POST /select/template_1/view/ => generated 16492 bytes in 127 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21365|app: 0|req: 4/7] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:17:35 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21368|app: 0|req: 4/8] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 18:17:36 2016] GET /select/template_1/view/ => generated 64802 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21365|app: 0|req: 5/9] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 18:17:43 2016] POST /select/template_1/analysis/ => generated 0 bytes in 159 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21368|app: 0|req: 5/10] 222.209.181.22 () {40 vars in 926 bytes} [Fri Feb 12 18:17:49 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21368|app: 0|req: 6/11] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:17:50 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21365|app: 0|req: 6/12] 222.209.181.22 () {44 vars in 1049 bytes} [Fri Feb 12 18:17:52 2016] GET /submit/welcome/realHandler/ => generated 15459 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21368|app: 0|req: 7/13] 222.209.181.22 () {42 vars in 1003 bytes} [Fri Feb 12 18:17:53 2016] GET /submit/welcome/realHandler/ => generated 15459 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21365|app: 0|req: 7/14] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 18:18:29 2016] GET /submit/welcome/realHandler/ => generated 15459 bytes in 20 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:19:42 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x18809d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x18809d0 pid: 21412 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21412, cores: 1)
spawned uWSGI worker 2 (pid: 21415, cores: 1)
[pid: 21412|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 18:19:44 2016] GET /submit/welcome/realHandler/ => generated 15549 bytes in 60 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:23:43 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x187e9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x187e9d0 pid: 21456 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21456, cores: 1)
spawned uWSGI worker 2 (pid: 21459, cores: 1)
[pid: 21456|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 18:23:45 2016] GET /submit/welcome/realHandler/ => generated 15710 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /mobile/
[pid: 21459|app: 0|req: 1/2] 203.208.60.220 () {40 vars in 658 bytes} [Fri Feb 12 18:28:29 2016] GET /mobile/ => generated 3126 bytes in 34 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:28:38 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ba99d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ba99d0 pid: 21505 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21505, cores: 1)
spawned uWSGI worker 2 (pid: 21508, cores: 1)
[pid: 21505|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 1079 bytes} [Fri Feb 12 18:28:47 2016] GET / => generated 218404 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1132 bytes} [Fri Feb 12 18:28:49 2016] GET /select/ => generated 1626 bytes in 37 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1161 bytes} [Fri Feb 12 18:28:50 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 2/4] 222.209.181.22 () {44 vars in 1182 bytes} [Fri Feb 12 18:28:52 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 3/5] 222.209.181.22 () {44 vars in 1171 bytes} [Fri Feb 12 18:29:45 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21505|app: 0|req: 3/6] 222.209.181.22 () {50 vars in 1300 bytes} [Fri Feb 12 18:29:45 2016] POST /select/template_1/view/ => generated 16735 bytes in 144 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21508|app: 0|req: 4/7] 222.209.181.22 () {44 vars in 1100 bytes} [Fri Feb 12 18:29:46 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 4/8] 222.209.181.22 () {44 vars in 1180 bytes} [Fri Feb 12 18:29:47 2016] GET /select/template_1/view/ => generated 64802 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 72, in analysis
    arr[i][0] = arr[i][0].replace("\"", "").decode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
[pid: 21508|app: 0|req: 5/9] 222.209.181.22 () {54 vars in 1360 bytes} [Fri Feb 12 18:29:55 2016] POST /select/template_1/analysis/ => generated 12528 bytes in 110 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 5/10] 222.209.181.22 () {40 vars in 941 bytes} [Fri Feb 12 18:30:11 2016] GET /select/template_1/view/ => generated 64802 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 72, in analysis
    arr[i][0] = arr[i][0].replace("\"", "").decode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[pid: 21508|app: 0|req: 6/11] 222.209.181.22 () {50 vars in 1174 bytes} [Fri Feb 12 18:30:19 2016] POST /select/template_1/analysis/ => generated 12218 bytes in 26 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 62, in analysis
    ans = ans[2:len(ans) - 2].split("],[")
TypeError: object of type 'NoneType' has no len()
[pid: 21505|app: 0|req: 6/12] 222.209.181.22 () {40 vars in 949 bytes} [Fri Feb 12 18:30:26 2016] GET /select/template_1/analysis/ => generated 56433 bytes in 78 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 7/13] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 18:31:13 2016] GET /select/template_1/ => generated 82701 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 7/14] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 18:31:15 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 8/15] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 18:31:32 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21505|app: 0|req: 8/16] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 18:31:32 2016] POST /select/template_1/view/ => generated 17086 bytes in 143 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21508|app: 0|req: 9/17] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 18:31:33 2016] GET /user_form_folders => generated 3156 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 9/18] 222.209.181.22 () {44 vars in 1180 bytes} [Fri Feb 12 18:31:36 2016] GET /select/template_1/view/ => generated 65005 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 72, in analysis
    arr[i][0] = arr[i][0].replace("\"", "").decode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[pid: 21508|app: 0|req: 10/19] 222.209.181.22 () {54 vars in 1360 bytes} [Fri Feb 12 18:31:45 2016] POST /select/template_1/analysis/ => generated 12522 bytes in 24 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 21505|app: 0|req: 10/20] 222.209.181.22 () {40 vars in 941 bytes} [Fri Feb 12 18:31:55 2016] GET /select/template_1/view/ => generated 65005 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21508|app: 0|req: 11/21] 222.209.181.22 () {40 vars in 941 bytes} [Fri Feb 12 18:31:55 2016] GET /select/template_1/view/ => generated 65005 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 72, in analysis
    arr[i][0] = arr[i][0].replace("\"", "").decode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[pid: 21505|app: 0|req: 11/22] 222.209.181.22 () {50 vars in 1174 bytes} [Fri Feb 12 18:32:02 2016] POST /select/template_1/analysis/ => generated 12218 bytes in 26 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /a.html
[pid: 21508|app: 0|req: 12/23] 180.109.136.239 () {32 vars in 378 bytes} [Fri Feb 12 18:34:08 2016] GET /a.html => generated 3120 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:34:35 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f1c9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f1c9d0 pid: 21549 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21549, cores: 1)
spawned uWSGI worker 2 (pid: 21552, cores: 1)
[pid: 21549|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 895 bytes} [Fri Feb 12 18:34:38 2016] GET / => generated 218404 bytes in 47 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21552|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 948 bytes} [Fri Feb 12 18:34:40 2016] GET /select/ => generated 1626 bytes in 34 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21549|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 977 bytes} [Fri Feb 12 18:34:41 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21552|app: 0|req: 2/4] 222.209.181.22 () {42 vars in 998 bytes} [Fri Feb 12 18:34:42 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21552|app: 0|req: 3/5] 222.209.181.22 () {42 vars in 987 bytes} [Fri Feb 12 18:35:02 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21549|app: 0|req: 3/6] 222.209.181.22 () {50 vars in 1168 bytes} [Fri Feb 12 18:35:02 2016] POST /select/template_1/view/ => generated 17029 bytes in 126 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21552|app: 0|req: 4/7] 222.209.181.22 () {44 vars in 962 bytes} [Fri Feb 12 18:35:02 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21549|app: 0|req: 4/8] 222.209.181.22 () {42 vars in 995 bytes} [Fri Feb 12 18:35:03 2016] GET /select/template_1/view/ => generated 65176 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 72, in analysis
    arr[i][0] = chr(arr[i][0].replace("\"", ""))
TypeError: an integer is required
[pid: 21552|app: 0|req: 5/9] 222.209.181.22 () {50 vars in 1174 bytes} [Fri Feb 12 18:35:07 2016] POST /select/template_1/analysis/ => generated 12065 bytes in 32 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:37:42 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd359d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd359d0 pid: 21596 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21596, cores: 1)
spawned uWSGI worker 2 (pid: 21599, cores: 1)
[pid: 21596|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 979 bytes} [Fri Feb 12 18:37:48 2016] GET /select/template_1/ => generated 82701 bytes in 45 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21599|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1000 bytes} [Fri Feb 12 18:37:55 2016] GET /select/template_1/edit/ => generated 23913 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21596|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 989 bytes} [Fri Feb 12 18:38:35 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21596|app: 0|req: 3/4] 222.209.181.22 () {50 vars in 1170 bytes} [Fri Feb 12 18:38:35 2016] POST /select/template_1/view/ => generated 120 bytes in 122 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21599|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 964 bytes} [Fri Feb 12 18:38:35 2016] GET /user_form_folders => generated 3156 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:42:21 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9f69d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9f69d0 pid: 21640 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21640, cores: 1)
spawned uWSGI worker 2 (pid: 21643, cores: 1)
[pid: 21640|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 978 bytes} [Fri Feb 12 18:42:23 2016] GET /select/template_1/ => generated 82701 bytes in 43 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21643|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 999 bytes} [Fri Feb 12 18:42:25 2016] GET /select/template_1/edit/ => generated 23884 bytes in 47 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21640|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 18:42:40 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21640|app: 0|req: 3/4] 222.209.181.22 () {50 vars in 1169 bytes} [Fri Feb 12 18:42:40 2016] POST /select/template_1/view/ => generated 16552 bytes in 126 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21643|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:42:40 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21640|app: 0|req: 4/6] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 18:42:43 2016] GET /select/template_1/view/ => generated 64747 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21643|app: 0|req: 3/7] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 18:42:50 2016] POST /select/template_1/analysis/ => generated 17 bytes in 273 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 18:48:34 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x25be9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x25be9d0 pid: 21687 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21687, cores: 1)
spawned uWSGI worker 2 (pid: 21690, cores: 1)
[pid: 21687|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 978 bytes} [Fri Feb 12 18:48:38 2016] GET /select/template_1/ => generated 82701 bytes in 42 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21690|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 999 bytes} [Fri Feb 12 18:48:40 2016] GET /select/template_1/edit/ => generated 23884 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21687|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 18:48:55 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21687|app: 0|req: 3/4] 222.209.181.22 () {50 vars in 1169 bytes} [Fri Feb 12 18:48:55 2016] POST /select/template_1/view/ => generated 16660 bytes in 130 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21690|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:48:55 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21687|app: 0|req: 4/6] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 18:48:57 2016] GET /select/template_1/view/ => generated 64829 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21687|app: 0|req: 5/7] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 18:49:02 2016] GET /submit/welcome/ => generated 12519 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21690|app: 0|req: 3/8] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 18:49:02 2016] POST /select/template_1/analysis/ => generated 17 bytes in 205 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21687|app: 0|req: 6/9] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 18:49:03 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21690|app: 0|req: 4/10] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 18:49:07 2016] GET /submit/welcome/realHandler/ => generated 15610 bytes in 18 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21687|app: 0|req: 7/11] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 18:49:07 2016] GET /submit/welcome/realHandler/ => generated 15610 bytes in 19 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21690|app: 0|req: 5/12] 203.208.60.156 () {40 vars in 654 bytes} [Fri Feb 12 18:52:58 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:05:18 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15b49d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15b49d0 pid: 21737 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21737, cores: 1)
spawned uWSGI worker 2 (pid: 21740, cores: 1)
[pid: 21737|app: 0|req: 1/1] 222.209.181.22 () {42 vars in 949 bytes} [Fri Feb 12 19:05:24 2016] GET /select/ => generated 1626 bytes in 39 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21740|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 978 bytes} [Fri Feb 12 19:05:25 2016] GET /select/template_1/ => generated 82701 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21737|app: 0|req: 2/3] 222.209.181.22 () {42 vars in 999 bytes} [Fri Feb 12 19:05:27 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21737|app: 0|req: 3/4] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 19:05:42 2016] GET /select/success/ => generated 14374 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 21740|app: 0|req: 2/5] 222.209.181.22 () {50 vars in 1169 bytes} [Fri Feb 12 19:05:42 2016] POST /select/template_1/view/ => generated 16678 bytes in 119 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21737|app: 0|req: 4/6] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 19:05:43 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21740|app: 0|req: 3/7] 222.209.181.22 () {42 vars in 996 bytes} [Fri Feb 12 19:05:44 2016] GET /select/template_1/view/ => generated 64829 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21740|app: 0|req: 4/8] 222.209.181.22 () {42 vars in 988 bytes} [Fri Feb 12 19:05:53 2016] GET /submit/welcome/ => generated 12519 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21737|app: 0|req: 5/9] 222.209.181.22 () {50 vars in 1175 bytes} [Fri Feb 12 19:05:53 2016] POST /select/template_1/analysis/ => generated 20 bytes in 174 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 21740|app: 0|req: 5/10] 222.209.181.22 () {44 vars in 963 bytes} [Fri Feb 12 19:05:54 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 21737|app: 0|req: 6/11] 222.209.181.22 () {44 vars in 1049 bytes} [Fri Feb 12 19:06:02 2016] GET /submit/welcome/realHandler/ => generated 15639 bytes in 24 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21740|app: 0|req: 6/12] 222.209.181.22 () {42 vars in 1003 bytes} [Fri Feb 12 19:06:02 2016] GET /submit/welcome/realHandler/ => generated 15639 bytes in 27 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:08:36 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x18f59d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x18f59d0 pid: 21781 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21781, cores: 1)
spawned uWSGI worker 2 (pid: 21784, cores: 1)
[pid: 21781|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:08:38 2016] GET /submit/welcome/realHandler/ => generated 15789 bytes in 58 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:10:43 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x24939d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x24939d0 pid: 21825 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21825, cores: 1)
spawned uWSGI worker 2 (pid: 21828, cores: 1)
[pid: 21825|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:10:44 2016] GET /submit/welcome/realHandler/ => generated 15900 bytes in 67 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:12:34 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x261e9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x261e9d0 pid: 21869 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21869, cores: 1)
spawned uWSGI worker 2 (pid: 21872, cores: 1)
[pid: 21869|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:12:36 2016] GET /submit/welcome/realHandler/ => generated 15862 bytes in 58 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:13:43 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x18019d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x18019d0 pid: 21913 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21913, cores: 1)
spawned uWSGI worker 2 (pid: 21916, cores: 1)
[pid: 21913|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:13:45 2016] GET /submit/welcome/realHandler/ => generated 15913 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 21916|app: 0|req: 1/2] 220.181.108.76 () {36 vars in 472 bytes} [Fri Feb 12 19:14:33 2016] GET / => generated 218404 bytes in 41 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:16:34 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc469d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xc469d0 pid: 21960 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 21960, cores: 1)
spawned uWSGI worker 2 (pid: 21963, cores: 1)
[pid: 21960|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:16:36 2016] GET /submit/welcome/realHandler/ => generated 15911 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:22:55 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x26329d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x26329d0 pid: 22007 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22007, cores: 1)
spawned uWSGI worker 2 (pid: 22010, cores: 1)
[pid: 22007|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:22:58 2016] GET /submit/welcome/realHandler/ => generated 15658 bytes in 61 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:24:38 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x13e99d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13e99d0 pid: 22052 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22052, cores: 1)
spawned uWSGI worker 2 (pid: 22055, cores: 1)
[pid: 22052|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:24:39 2016] GET /submit/welcome/realHandler/ => generated 15670 bytes in 60 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:26:55 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x14949d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x14949d0 pid: 22106 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22106, cores: 1)
spawned uWSGI worker 2 (pid: 22109, cores: 1)
[pid: 22106|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:26:57 2016] GET /submit/welcome/realHandler/ => generated 15667 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:28:18 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x21779d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x21779d0 pid: 22150 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22150, cores: 1)
spawned uWSGI worker 2 (pid: 22153, cores: 1)
[pid: 22150|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:28:20 2016] GET /submit/welcome/realHandler/ => generated 15789 bytes in 60 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 22153|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:28:26 2016] GET /submit/welcome/realHandler/ => generated 15789 bytes in 69 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 22150|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:29:57 2016] GET /submit/welcome/realHandler/ => generated 15789 bytes in 22 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:30:25 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x13a59d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13a59d0 pid: 22194 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22194, cores: 1)
spawned uWSGI worker 2 (pid: 22197, cores: 1)
[pid: 22194|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:30:31 2016] GET /submit/welcome/realHandler/ => generated 15784 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:32:16 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc6a9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xc6a9d0 pid: 22238 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22238, cores: 1)
spawned uWSGI worker 2 (pid: 22241, cores: 1)
[pid: 22238|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:32:19 2016] GET /submit/welcome/realHandler/ => generated 15879 bytes in 60 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:32:53 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a979d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a979d0 pid: 22282 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22282, cores: 1)
spawned uWSGI worker 2 (pid: 22285, cores: 1)
[pid: 22282|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:32:55 2016] GET /submit/welcome/realHandler/ => generated 15879 bytes in 59 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:35:02 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xeff9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xeff9d0 pid: 22329 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22329, cores: 1)
spawned uWSGI worker 2 (pid: 22332, cores: 1)
[pid: 22329|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:35:04 2016] GET /submit/welcome/realHandler/ => generated 15763 bytes in 62 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:37:08 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x19139d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19139d0 pid: 22373 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22373, cores: 1)
spawned uWSGI worker 2 (pid: 22376, cores: 1)
[pid: 22373|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:37:10 2016] GET /submit/welcome/realHandler/ => generated 15762 bytes in 57 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 22376|app: 0|req: 1/2] 179.255.163.83 () {40 vars in 655 bytes} [Fri Feb 12 19:38:31 2016] GET / => generated 218404 bytes in 43 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:41:37 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xbec9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xbec9d0 pid: 22417 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22417, cores: 1)
spawned uWSGI worker 2 (pid: 22420, cores: 1)
[pid: 22417|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:41:40 2016] GET /submit/welcome/realHandler/ => generated 15851 bytes in 61 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 19:42:50 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x157b9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x157b9d0 pid: 22461 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 22461, cores: 1)
spawned uWSGI worker 2 (pid: 22464, cores: 1)
[pid: 22461|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1034 bytes} [Fri Feb 12 19:42:53 2016] GET /submit/welcome/realHandler/ => generated 15841 bytes in 58 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
