*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:36:46 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe389d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe389d0 pid: 20844 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20844, cores: 1)
spawned uWSGI worker 2 (pid: 20847, cores: 1)
[pid: 20844|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 874 bytes} [Fri Feb 12 17:36:48 2016] GET / => generated 218404 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1057 bytes} [Fri Feb 12 17:37:00 2016] GET / => generated 218404 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1110 bytes} [Fri Feb 12 17:37:02 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 3/4] 222.209.181.22 () {44 vars in 1139 bytes} [Fri Feb 12 17:37:03 2016] GET /select/template_1/ => generated 82701 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 1160 bytes} [Fri Feb 12 17:37:05 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 4/6] 222.209.181.22 () {44 vars in 1149 bytes} [Fri Feb 12 17:37:39 2016] GET /select/success/ => generated 14374 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20847|app: 0|req: 3/7] 222.209.181.22 () {50 vars in 1278 bytes} [Fri Feb 12 17:37:39 2016] POST /select/template_1/view/ => generated 16818 bytes in 104 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20844|app: 0|req: 5/8] 222.209.181.22 () {44 vars in 1078 bytes} [Fri Feb 12 17:37:40 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20847|app: 0|req: 4/9] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:37:45 2016] GET /select/template_1/view/ => generated 64827 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20844|app: 0|req: 6/10] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:37:45 2016] GET /select/template_1/view/ => generated 64827 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 87, in analysis
    s = UserDefine.objects.get(username="Hang").statics_set.get(key=foreign_key)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 20847|app: 0|req: 5/11] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:37:54 2016] POST /select/template_1/analysis/ => generated 12415 bytes in 35 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:41:12 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15c99d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15c99d0 pid: 20888 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20888, cores: 1)
spawned uWSGI worker 2 (pid: 20891, cores: 1)
[pid: 20888|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:41:16 2016] GET /select/template_1/view/ => generated 64827 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20891|app: 0|req: 1/2] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:41:28 2016] GET /select/template_1/ => generated 82701 bytes in 36 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20888|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:41:30 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20891|app: 0|req: 2/4] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:42:08 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20888|app: 0|req: 3/5] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:42:08 2016] POST /select/template_1/view/ => generated 16777 bytes in 179 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20891|app: 0|req: 3/6] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:42:09 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20888|app: 0|req: 4/7] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:42:14 2016] GET /select/template_1/view/ => generated 64779 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/analysis/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 77, in analysis
    if UserDefine.objects.get(username="Hang").statics_set.get(key='arr[0][0]'):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 20891|app: 0|req: 4/8] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:42:24 2016] POST /select/template_1/analysis/ => generated 12403 bytes in 38 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:45:32 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xec09d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xec09d0 pid: 20935 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20935, cores: 1)
spawned uWSGI worker 2 (pid: 20938, cores: 1)
[pid: 20935|app: 0|req: 1/1] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:45:40 2016] GET /select/template_1/view/ => generated 64779 bytes in 46 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1080 bytes} [Fri Feb 12 17:45:53 2016] GET / => generated 218404 bytes in 45 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 2/3] 222.209.181.22 () {44 vars in 1133 bytes} [Fri Feb 12 17:45:55 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 3/4] 222.209.181.22 () {44 vars in 1162 bytes} [Fri Feb 12 17:45:56 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 2/5] 222.209.181.22 () {44 vars in 1183 bytes} [Fri Feb 12 17:45:58 2016] GET /select/template_1/edit/ => generated 23884 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 3/6] 222.209.181.22 () {44 vars in 1172 bytes} [Fri Feb 12 17:46:35 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 20935|app: 0|req: 4/7] 222.209.181.22 () {50 vars in 1301 bytes} [Fri Feb 12 17:46:35 2016] POST /select/template_1/view/ => generated 16705 bytes in 140 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20938|app: 0|req: 4/8] 222.209.181.22 () {44 vars in 1101 bytes} [Fri Feb 12 17:46:36 2016] GET /user_form_folders => generated 3156 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 5/9] 222.209.181.22 () {40 vars in 920 bytes} [Fri Feb 12 17:46:42 2016] GET /select/template_1/view/ => generated 64743 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20938|app: 0|req: 5/10] 222.209.181.22 () {50 vars in 1153 bytes} [Fri Feb 12 17:46:53 2016] POST /select/template_1/analysis/ => generated 0 bytes in 156 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20935|app: 0|req: 6/11] 222.209.181.22 () {40 vars in 904 bytes} [Fri Feb 12 17:47:21 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 20935|app: 0|req: 7/12] 222.209.181.22 () {44 vars in 941 bytes} [Fri Feb 12 17:47:22 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 140, in real_handler
    dim_arr[h] = int(dim_arr[h])
ValueError: invalid literal for int() with base 10: ''
[pid: 20938|app: 0|req: 6/13] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 17:47:25 2016] GET /submit/welcome/realHandler/ => generated 58074 bytes in 95 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 140, in real_handler
    dim_arr[h] = int(dim_arr[h])
ValueError: invalid literal for int() with base 10: ''
[pid: 20935|app: 0|req: 8/14] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 17:47:25 2016] GET /submit/welcome/realHandler/ => generated 57924 bytes in 83 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 17:49:04 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x23c79d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x23c79d0 pid: 20979 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 20979, cores: 1)
spawned uWSGI worker 2 (pid: 20982, cores: 1)
[pid: 20979|app: 0|req: 1/1] 222.209.181.22 () {44 vars in 1050 bytes} [Fri Feb 12 17:49:10 2016] GET /submit/welcome/realHandler/ => generated 15467 bytes in 50 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 20982|app: 0|req: 1/2] 222.209.181.22 () {42 vars in 1004 bytes} [Fri Feb 12 17:49:10 2016] GET /submit/welcome/realHandler/ => generated 15467 bytes in 42 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
