*** Starting uWSGI 2.0.11.2 (64bit) on [Thu Jan 28 22:43:50 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib/Questionnaire
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x105a9d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x105a9d0 pid: 1142 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1142, cores: 1)
spawned uWSGI worker 2 (pid: 1145, cores: 1)
[pid: 1142|app: 0|req: 1/1] 171.221.114.138 () {42 vars in 822 bytes} [Thu Jan 28 22:44:02 2016] GET / => generated 218284 bytes in 43 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1145|app: 0|req: 1/2] 171.221.114.138 () {48 vars in 967 bytes} [Thu Jan 28 22:44:02 2016] GET / => generated 218284 bytes in 43 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 2/3] 171.221.114.138 () {44 vars in 875 bytes} [Thu Jan 28 22:44:05 2016] GET /select/ => generated 1506 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 3/4] 171.221.114.138 () {44 vars in 904 bytes} [Thu Jan 28 22:44:06 2016] GET /select/template_1/ => generated 82638 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1145|app: 0|req: 2/5] 171.221.114.138 () {44 vars in 925 bytes} [Thu Jan 28 22:44:08 2016] GET /select/template_1/edit/ => generated 22878 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 1145|app: 0|req: 3/6] 171.221.114.138 () {44 vars in 930 bytes} [Thu Jan 28 22:44:16 2016] GET /select/template_1/view/ => generated 2054 bytes in 24 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 4/7] 171.221.114.138 () {50 vars in 1043 bytes} [Thu Jan 28 22:44:16 2016] POST /select/template_1/view/ => generated 12945 bytes in 56 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 1145|app: 0|req: 4/8] 171.221.114.138 () {44 vars in 904 bytes} [Thu Jan 28 22:49:58 2016] GET /select/template_1/ => generated 82638 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 5/9] 171.221.114.138 () {44 vars in 925 bytes} [Thu Jan 28 22:50:00 2016] GET /select/template_1/edit/ => generated 22878 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
[pid: 1145|app: 0|req: 5/10] 171.221.114.138 () {50 vars in 1041 bytes} [Thu Jan 28 22:50:03 2016] POST /select/template_1/view/ => generated 12182 bytes in 46 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 41, in view
    return render_to_response('Success.html', {'pageForm': UserDefine.objects.get(username="Hang").pageForm})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one UserDefine -- it returned 2!
[pid: 1142|app: 0|req: 6/11] 171.221.114.138 () {44 vars in 930 bytes} [Thu Jan 28 22:50:03 2016] GET /select/template_1/view/ => generated 64085 bytes in 86 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
[pid: 1145|app: 0|req: 6/12] 171.221.114.138 () {44 vars in 904 bytes} [Thu Jan 28 22:51:03 2016] GET /select/template_1/ => generated 82638 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 7/13] 171.221.114.138 () {44 vars in 925 bytes} [Thu Jan 28 22:51:05 2016] GET /select/template_1/edit/ => generated 22878 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view question_naire.views.view didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 41, in view
    return render_to_response('Success.html', {'pageForm': UserDefine.objects.get(username="Hang").pageForm})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one UserDefine -- it returned 3!
[pid: 1145|app: 0|req: 7/14] 171.221.114.138 () {50 vars in 1043 bytes} [Thu Jan 28 22:51:11 2016] POST /select/template_1/view/ => generated 12819 bytes in 69 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
[pid: 1142|app: 0|req: 8/15] 171.221.114.138 () {44 vars in 930 bytes} [Thu Jan 28 22:51:11 2016] GET /select/template_1/view/ => generated 64137 bytes in 127 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
