*** Starting uWSGI 2.0.11.2 (64bit) on [Fri Feb 12 14:39:52 2016] ***
compiled with version: 4.8.2 on 06 December 2015 10:28:08
os: Linux-3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
nodename: iZ28zgwg61iZ
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/git-lib/Questionnaire
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/git-lib/Questionnaire
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7770
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8077 fd 3
Python version: 2.7.6 (default, Mar 22 2014, 23:03:41)  [GCC 4.8.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xfc39d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xfc39d0 pid: 19365 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 19365, cores: 1)
spawned uWSGI worker 2 (pid: 19368, cores: 1)
[pid: 19365|app: 0|req: 1/1] 222.209.181.235 () {42 vars in 1059 bytes} [Fri Feb 12 14:40:19 2016] GET / => generated 218404 bytes in 49 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19368|app: 0|req: 1/2] 222.209.181.235 () {42 vars in 1059 bytes} [Fri Feb 12 14:40:19 2016] GET / => generated 218404 bytes in 44 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19365|app: 0|req: 2/3] 123.125.71.109 () {38 vars in 537 bytes} [Fri Feb 12 14:54:45 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /a.html
[pid: 19365|app: 0|req: 3/4] 180.109.136.239 () {32 vars in 379 bytes} [Fri Feb 12 14:58:11 2016] GET /a.html => generated 3120 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /a.html
[pid: 19368|app: 0|req: 2/5] 180.109.136.239 () {32 vars in 379 bytes} [Fri Feb 12 14:58:14 2016] GET /a.html => generated 3120 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /azenv.php
[pid: 19365|app: 0|req: 4/6] 5.178.86.75 () {40 vars in 712 bytes} [Fri Feb 12 14:58:22 2016] POST /azenv.php?auth=145526030299&a=PSCN&i=1926723903&p=80 => generated 3194 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /a.html
[pid: 19368|app: 0|req: 3/7] 180.109.136.239 () {32 vars in 379 bytes} [Fri Feb 12 14:58:23 2016] GET /a.html => generated 3120 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /testproxy.php
[pid: 19365|app: 0|req: 5/8] 185.49.14.190 () {38 vars in 629 bytes} [Fri Feb 12 15:09:04 2016] GET /testproxy.php => generated 3151 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 19368|app: 0|req: 4/9] 220.181.108.91 () {36 vars in 472 bytes} [Fri Feb 12 15:14:58 2016] GET / => generated 218404 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19365|app: 0|req: 6/10] 222.209.181.22 () {44 vars in 1111 bytes} [Fri Feb 12 15:15:51 2016] GET /select/ => generated 1626 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19365|app: 0|req: 7/11] 222.209.181.22 () {44 vars in 1140 bytes} [Fri Feb 12 15:15:53 2016] GET /select/template_1/ => generated 82701 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19368|app: 0|req: 5/12] 222.209.181.22 () {44 vars in 1161 bytes} [Fri Feb 12 15:15:57 2016] GET /select/template_1/edit/ => generated 23858 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19365|app: 0|req: 8/13] 123.125.71.56 () {36 vars in 471 bytes} [Fri Feb 12 15:17:15 2016] GET / => generated 218404 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 19368|app: 0|req: 6/14] 222.209.181.22 () {44 vars in 1150 bytes} [Fri Feb 12 15:18:04 2016] GET /select/success/ => generated 14374 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /select/template_1/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 47, in view
    s = u.statics_set.get(key='arr[0][0]')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 19368|app: 0|req: 7/15] 222.209.181.22 () {50 vars in 1281 bytes} [Fri Feb 12 15:18:04 2016] POST /select/template_1/view/ => generated 21289 bytes in 69 msecs (HTTP/1.1 500) 2 headers in 93 bytes (1 switches on core 0)
Not Found: /user_form_folders
[pid: 19365|app: 0|req: 9/16] 222.209.181.22 () {44 vars in 1079 bytes} [Fri Feb 12 15:18:05 2016] GET /user_form_folders => generated 3156 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 19368|app: 0|req: 8/17] 222.209.181.22 () {44 vars in 1180 bytes} [Fri Feb 12 15:18:07 2016] GET /select/template_1/view/ => generated 69232 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 138, in real_handler
    s = UserDefine.objects.get(username="Hang").statics_set.get(key='arr[0][0]')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 19365|app: 0|req: 10/18] 222.209.181.22 () {44 vars in 1188 bytes} [Fri Feb 12 15:18:14 2016] GET /submit/welcome/realHandler/ => generated 65888 bytes in 108 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Internal Server Error: /submit/welcome/realHandler/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./question_naire/views.py", line 138, in real_handler
    s = UserDefine.objects.get(username="Hang").statics_set.get(key='arr[0][0]')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: Statics matching query does not exist.
[pid: 19368|app: 0|req: 9/19] 222.209.181.22 () {44 vars in 1188 bytes} [Fri Feb 12 15:18:15 2016] GET /submit/welcome/realHandler/ => generated 65888 bytes in 95 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 19365|app: 0|req: 11/20] 222.209.181.22 () {42 vars in 1062 bytes} [Fri Feb 12 15:18:15 2016] GET /favicon.ico => generated 3138 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
